# Example using a public action
on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: dinomite505/javascript-actions@v1.1
        with:
          who-to-greet: 'Dino The Greatest'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"